default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: "rnters"
  username: "postgres"
  password: ""
  host: "postgres"
  port: "5432"
  pool: "5"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
